#!/bin/bash

mpaso_path="/home/qingli/models/MPAS-Model"

# target="gfortran"
# target="clean"
target=$1

# set env
export NETCDF=/home/qingli/local/netcdf
export PNETCDF=/home/qingli/local/pnetcdf
export PIO=/home/qingli/local/pio
export FFTW=/home/qingli/local/fftw
export CUDA=/home/qingli/local/pgi/linux86-64/2019/cuda/10.1
export PGI=/home/qingli/local/pgi/linux86-64/2019

export LD_LIBRARY_PATH=$PGI/lib:$CUDA/lib64:$LD_LIBRARY_PATH

export AUTOCLEAN=true
export CORE=ocean
export USE_PIO2=false

if [[ $2 == "debug" ]]; then
    export DEBUG=true
else
    export DEBUG=false
fi

cd ${mpaso_path}
make ${target}
