#!/bin/bash

mpaso_path=../MPAS-Model

# target="gfortran"
# target="clean"
target=$1

# set env
export PREFIX="${HOME}/miniconda3/envs/mpas"
export MPAS_EXTERNAL_LIBS="-L${PREFIX}/lib -lnetcdff"
export NETCDF=${PREFIX}
export PNETCDF=${PREFIX}
export PIO=${PREFIX}
export FFTW=${PREFIX}
export AUTOCLEAN=true
export CORE=ocean
export USE_PIO2=false

if [[ $2 == "debug" ]]; then
    export DEBUG=true
else
    export DEBUG=false
fi

cd ${mpaso_path}
make ${target}
