#!/bin/bash

mpaso_path="../MPAS-Model"

# target="gfortran"
# target="clean"
target=$1

# set env
source ./set_env_pgi.sh

if [[ $2 == "debug" ]]; then
    export DEBUG=true
else
    export DEBUG=false
fi

cd ${mpaso_path}
make ${target}
