#!/bin/bash

run_path="/home/qingli/scratch/mpas"
casename=sp_mle_test
# run_path="/home/qingli/scratch/superparameterization"
# casename=sp_single_column

# set env
export NETCDF=/home/qingli/local/netcdf
export PNETCDF=/home/qingli/local/pnetcdf
export PIO=/home/qingli/local/pio
export FFTW=/home/qingli/local/fftw
export CUDA=/home/qingli/local/pgi/linux86-64/2019/cuda/10.1
export PGI=/home/qingli/local/pgi/linux86-64/2019

export LD_LIBRARY_PATH=$PGI/lib:$CUDA/lib64:$LD_LIBRARY_PATH

cd ${run_path}/${casename}
mpirun -n 1 ./ocean_model -n namelist.ocean  -s streams.ocean > log.ocean.0 &
cd -

